export const ANGKOR_TEXTURES = {
  FLOOR_CLEAN: 'angkor_floor_clean',
  FLOOR_A: 'angkor_floor_a',
  FLOOR_B: 'angkor_floor_b',
  FLOOR_CRACKED: 'angkor_floor_cracked',
  FLOOR_MOSSY: 'angkor_floor_mossy',
  WALL_STRAIGHT: 'angkor_wall_straight',
  WALL_CORNER: 'angkor_wall_corner',
  WALL_INNER_PILLAR: 'angkor_wall_inner_pillar',
  WALL_EDGE: 'angkor_wall_edge',
  OVERLAY_MOSS: 'angkor_overlay_moss',
  OVERLAY_ROOTS: 'angkor_overlay_roots',
  OVERLAY_CRACKS: 'angkor_overlay_cracks',
  OVERLAY_FOLIAGE: 'angkor_overlay_foliage',
  BLUE_GEM: 'angkor_blue_gem',
  BOULDER: 'angkor_boulder',
  KEY: 'angkor_key',
  GATE_LOCKED: 'angkor_gate_locked',
  GATE_OPEN: 'angkor_gate_open',
  SHRINE: 'angkor_shrine',
  SPIKES: 'angkor_spikes',
  POISON: 'angkor_poison',
  SWORD: 'angkor_sword',
  POTION: 'angkor_potion',
  CHEST_CLOSED: 'angkor_chest_closed',
  CHEST_OPEN: 'angkor_chest_open',
  GOBLIN: 'goblin_framed',
} as const

export type AngkorTextureKey = typeof ANGKOR_TEXTURES[keyof typeof ANGKOR_TEXTURES]

export interface AssetMetadata {
  readonly key: AngkorTextureKey
  readonly path: string
  readonly sourceDimensions: { readonly width: number; readonly height: number }
  readonly logicalFootprint: string
  readonly recommendedAnchor: { readonly x: number; readonly y: number }
  readonly displayScale: number
  readonly defaultDepth: number
}

export const ANGKOR_DEPTH = {
  BASE_FLOOR: 1,
  FLOOR_OVERLAYS: 2,
  OVERLAYS: 2,
  HAZARDS: 3,
  COLLECTIBLES: 4,
  WALLS: 5,
  PROPS: 6,
  BOULDER: 7,
  PLAYER: 8,
  FOREGROUND_OVERLAYS: 9,
  FOREGROUND: 9,
  EFFECTS: 10,
} as const

export const ANGKOR_ASSETS: readonly AssetMetadata[] = [
  {
    key: ANGKOR_TEXTURES.FLOOR_CLEAN,
    path: '/assets/game/angkor/environment/floor-clean.png',
    sourceDimensions: { width: 256, height: 256 },
    logicalFootprint: '1×1',
    recommendedAnchor: { x: 0.5, y: 0.5 },
    displayScale: 32 / 256,
    defaultDepth: ANGKOR_DEPTH.BASE_FLOOR,
  },
  {
    key: ANGKOR_TEXTURES.FLOOR_A,
    path: '/assets/game/angkor/environment/floor-variation-a.png',
    sourceDimensions: { width: 256, height: 256 },
    logicalFootprint: '1×1',
    recommendedAnchor: { x: 0.5, y: 0.5 },
    displayScale: 32 / 256,
    defaultDepth: ANGKOR_DEPTH.BASE_FLOOR,
  },
  {
    key: ANGKOR_TEXTURES.FLOOR_B,
    path: '/assets/game/angkor/environment/floor-variation-b.png',
    sourceDimensions: { width: 256, height: 256 },
    logicalFootprint: '1×1',
    recommendedAnchor: { x: 0.5, y: 0.5 },
    displayScale: 32 / 256,
    defaultDepth: ANGKOR_DEPTH.BASE_FLOOR,
  },
  {
    key: ANGKOR_TEXTURES.FLOOR_CRACKED,
    path: '/assets/game/angkor/environment/floor-cracked.png',
    sourceDimensions: { width: 256, height: 256 },
    logicalFootprint: '1×1',
    recommendedAnchor: { x: 0.5, y: 0.5 },
    displayScale: 32 / 256,
    defaultDepth: ANGKOR_DEPTH.BASE_FLOOR,
  },
  {
    key: ANGKOR_TEXTURES.FLOOR_MOSSY,
    path: '/assets/game/angkor/environment/floor-mossy.png',
    sourceDimensions: { width: 256, height: 256 },
    logicalFootprint: '1×1',
    recommendedAnchor: { x: 0.5, y: 0.5 },
    displayScale: 32 / 256,
    defaultDepth: ANGKOR_DEPTH.BASE_FLOOR,
  },
  {
    key: ANGKOR_TEXTURES.WALL_STRAIGHT,
    path: '/assets/game/angkor/environment/wall-straight.png',
    sourceDimensions: { width: 256, height: 256 },
    logicalFootprint: '1×1',
    recommendedAnchor: { x: 0.5, y: 1.0 },
    displayScale: 32 / 256,
    defaultDepth: ANGKOR_DEPTH.WALLS,
  },
  {
    key: ANGKOR_TEXTURES.WALL_CORNER,
    path: '/assets/game/angkor/environment/wall-corner.png',
    sourceDimensions: { width: 256, height: 256 },
    logicalFootprint: '1×1',
    recommendedAnchor: { x: 0.5, y: 1.0 },
    displayScale: 32 / 256,
    defaultDepth: ANGKOR_DEPTH.WALLS,
  },
  {
    key: ANGKOR_TEXTURES.WALL_INNER_PILLAR,
    path: '/assets/game/angkor/environment/wall-inner-pillar.png',
    sourceDimensions: { width: 256, height: 256 },
    logicalFootprint: '1×1',
    recommendedAnchor: { x: 0.5, y: 1.0 },
    displayScale: 32 / 256,
    defaultDepth: ANGKOR_DEPTH.WALLS,
  },
  {
    key: ANGKOR_TEXTURES.WALL_EDGE,
    path: '/assets/game/angkor/environment/wall-edge.png',
    sourceDimensions: { width: 256, height: 256 },
    logicalFootprint: '1×1',
    recommendedAnchor: { x: 0.5, y: 1.0 },
    displayScale: 32 / 256,
    defaultDepth: ANGKOR_DEPTH.WALLS,
  },
  {
    key: ANGKOR_TEXTURES.OVERLAY_MOSS,
    path: '/assets/game/angkor/overlays/overlay-moss.png',
    sourceDimensions: { width: 256, height: 256 },
    logicalFootprint: '1×1 overlay',
    recommendedAnchor: { x: 0.5, y: 0.5 },
    displayScale: 32 / 256,
    defaultDepth: ANGKOR_DEPTH.OVERLAYS,
  },
  {
    key: ANGKOR_TEXTURES.OVERLAY_ROOTS,
    path: '/assets/game/angkor/overlays/overlay-roots.png',
    sourceDimensions: { width: 256, height: 256 },
    logicalFootprint: '1×1 overlay',
    recommendedAnchor: { x: 0.5, y: 0.5 },
    displayScale: 32 / 256,
    defaultDepth: ANGKOR_DEPTH.OVERLAYS,
  },
  {
    key: ANGKOR_TEXTURES.OVERLAY_CRACKS,
    path: '/assets/game/angkor/overlays/overlay-cracks.png',
    sourceDimensions: { width: 256, height: 256 },
    logicalFootprint: '1×1 overlay',
    recommendedAnchor: { x: 0.5, y: 0.5 },
    displayScale: 32 / 256,
    defaultDepth: ANGKOR_DEPTH.OVERLAYS,
  },
  {
    key: ANGKOR_TEXTURES.OVERLAY_FOLIAGE,
    path: '/assets/game/angkor/overlays/overlay-foliage.png',
    sourceDimensions: { width: 256, height: 256 },
    logicalFootprint: '1×1 overlay',
    recommendedAnchor: { x: 0.5, y: 0.5 },
    displayScale: 32 / 256,
    defaultDepth: ANGKOR_DEPTH.OVERLAYS,
  },
  {
    key: ANGKOR_TEXTURES.BLUE_GEM,
    path: '/assets/game/angkor/props/blue-gem.png',
    sourceDimensions: { width: 256, height: 256 },
    logicalFootprint: '1×1',
    recommendedAnchor: { x: 0.5, y: 0.5 },
    displayScale: 22 / 256,
    defaultDepth: ANGKOR_DEPTH.COLLECTIBLES,
  },
  {
    key: ANGKOR_TEXTURES.BOULDER,
    path: '/assets/game/angkor/props/pushable-boulder.png',
    sourceDimensions: { width: 256, height: 256 },
    logicalFootprint: '1×1',
    recommendedAnchor: { x: 0.5, y: 0.5 },
    displayScale: 28 / 256,
    defaultDepth: ANGKOR_DEPTH.BOULDER,
  },
  {
    key: ANGKOR_TEXTURES.KEY,
    path: '/assets/game/angkor/props/temple-key.png',
    sourceDimensions: { width: 256, height: 256 },
    logicalFootprint: '1×1',
    recommendedAnchor: { x: 0.5, y: 0.5 },
    displayScale: 24 / 256,
    defaultDepth: ANGKOR_DEPTH.COLLECTIBLES,
  },
  {
    key: ANGKOR_TEXTURES.GATE_LOCKED,
    path: '/assets/game/angkor/props/temple-gate-locked.png',
    sourceDimensions: { width: 512, height: 512 },
    logicalFootprint: '1×1 doorway collision',
    recommendedAnchor: { x: 0.5, y: 1.0 },
    displayScale: 58 / 512,
    defaultDepth: ANGKOR_DEPTH.PROPS,
  },
  {
    key: ANGKOR_TEXTURES.GATE_OPEN,
    path: '/assets/game/angkor/props/temple-gate-open.png',
    sourceDimensions: { width: 512, height: 512 },
    logicalFootprint: 'same footprint',
    recommendedAnchor: { x: 0.5, y: 1.0 },
    displayScale: 58 / 512,
    defaultDepth: ANGKOR_DEPTH.PROPS,
  },
  {
    key: ANGKOR_TEXTURES.SHRINE,
    path: '/assets/game/angkor/props/inner-shrine.png',
    sourceDimensions: { width: 384, height: 384 },
    logicalFootprint: '1×1 interaction tile; visual may exceed tile',
    recommendedAnchor: { x: 0.5, y: 1.0 },
    displayScale: 48 / 384,
    defaultDepth: ANGKOR_DEPTH.PROPS,
  },
  {
    key: ANGKOR_TEXTURES.SPIKES,
    path: '/assets/game/angkor/hazards/spike-trap.png',
    sourceDimensions: { width: 256, height: 256 },
    logicalFootprint: '1×1',
    recommendedAnchor: { x: 0.5, y: 0.5 },
    displayScale: 30 / 256,
    defaultDepth: ANGKOR_DEPTH.HAZARDS,
  },
  {
    key: ANGKOR_TEXTURES.POISON,
    path: '/assets/game/angkor/hazards/poison-hazard.png',
    sourceDimensions: { width: 256, height: 256 },
    logicalFootprint: '1×1',
    recommendedAnchor: { x: 0.5, y: 0.5 },
    displayScale: 30 / 256,
    defaultDepth: ANGKOR_DEPTH.HAZARDS,
  },
  {
    key: ANGKOR_TEXTURES.SWORD,
    path: '/assets/game/angkor/props/sword.png',
    sourceDimensions: { width: 256, height: 256 },
    logicalFootprint: '1×1',
    recommendedAnchor: { x: 0.5, y: 0.5 },
    displayScale: 24 / 256,
    defaultDepth: ANGKOR_DEPTH.COLLECTIBLES,
  },
  {
    key: ANGKOR_TEXTURES.POTION,
    path: '/assets/game/angkor/props/potion.png',
    sourceDimensions: { width: 256, height: 256 },
    logicalFootprint: '1×1',
    recommendedAnchor: { x: 0.5, y: 0.5 },
    displayScale: 24 / 256,
    defaultDepth: ANGKOR_DEPTH.COLLECTIBLES,
  },
  {
    key: ANGKOR_TEXTURES.CHEST_CLOSED,
    path: '/assets/game/angkor/props/chest-closed.png',
    sourceDimensions: { width: 256, height: 256 },
    logicalFootprint: '1×1',
    recommendedAnchor: { x: 0.5, y: 0.5 },
    displayScale: 28 / 256,
    defaultDepth: ANGKOR_DEPTH.PROPS,
  },
  {
    key: ANGKOR_TEXTURES.CHEST_OPEN,
    path: '/assets/game/angkor/props/chest-open.png',
    sourceDimensions: { width: 256, height: 256 },
    logicalFootprint: '1×1',
    recommendedAnchor: { x: 0.5, y: 0.5 },
    displayScale: 28 / 256,
    defaultDepth: ANGKOR_DEPTH.PROPS,
  },
]
